name: bsi
description: BakeCode Services Interconnect - Dart API
version: 0.0.2-alpha
homepage: https://github.com/crysalisdevs/bsi-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  mqtt_client: ^9.0.0
  equatable: ^2.0.0
