name: bsi_dart
description: The core of BakeCode.
version: 0.0.2-alpha

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  mqtt_client: ^9.3.2
  uuid: ^3.0.4
  yaml: ^3.1.0

dev_dependencies:
  lint: ^1.5.3
  meta: ^1.7.0
